### ISSUE TITLE
IDF - Israeli Defense Forces Units

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#132]
**Description:**
This is an IDF soldier pack including 5 custom helmets, helmet covers (miznefet), 4 caps and uniforms.
High quality models with baked normal maps.

**Download:** http://www.armaholic.com/page.php?id=20034
**Size:** 104MB

**Comment by karlkarl93** [comment]
Here is what the units look like and what type of spawnable units there are - http://imgur.com/a/HqtLs

Problems - They only seem to have green camo and they use the default arma 3 launchers, while it may not be a problem but to me some of them look out of place. (futuristic).

**Comment by abelarno** [comment]
The mod uses a lot of arma 3 vanilla elements, like the launcher and some vehicles. However that might actually be alright to use seeing how advanced the israeli military is.

The units don't have many spawnable groups in zeus. Hamas only has two technicals as spawnable group. The IDF only two infantry groups.

Hamas does not have much diversity. Only 3 different infantry, and 1 techincal. Only the rifleman is acutually spawnable in zeus.

The assests look good, and it all seems to work fine.

**Comment by TheGrandVizier** [comment]
A little note:
A very large portion of Vanilla gear is actually IDF gear.
LMGs, Rifles, Tanks, APCs, AA, A lot of things. The Launchers are one of them. The Titan launcher is a Rafael Industries launcher in reality named Mini-Spike (the latest model, previous ones are just Spike-XX).

So yea, it's not that IDF is so futurestic, it's just that Arma took most of it's arsenal from the IDF and distributed it between the factions. For example, the IND use Tavor rifles, while the BLUEFOR have Merkava Tanks and CSAT have Zafir LMG.

**Comment by TheGrandVizier** [comment]
Regarding camo:

**Comment by LordCavac** [comment]
The APC is affected by the RHS acceleration bug. There was an issue I had in my initial test where after spawning the troops through the mission editor there would be a backpack permanently floating in the air anywhere I placed a sniper, but I haven't been able to replicate it thus far so I don't have a screenshot. Their arms to clip into their bodies every model has this problem but some are worse than others. Otherwise I found no issues.
![2016-03-02_00001](https://cloud.githubusercontent.com/assets/16757011/13459237/ba38d1e0-e0b5-11e5-98cd-10727558f9a6.jpg)

**Comment by Fourjays** [comment]
I would be sure to test this alongside the latest RHS (new modpack). But it is unclear how RHS could have anything to do with this, as this mod uses vanilla vehicles doesn't it?

**Comment by TheGrandVizier** [comment]
(Real) IDF uses m113 which ingame is available through rhs.

**Comment by Ludvigroosen** [comment]
Gonna test this today if i have the time for it.

**Comment by Ludvigroosen** [comment]
@Fourjays mod is no longer in development and got RHS v0.3.8 as a dependency. Doing a review and some testing on this.

**Comment by Ludvigroosen** [comment]
**Compatibility** (If it compatible with the mod pack)
Compatible with mod pack, no issues what I could find with ACE (Changed tiers) and no "new" error messages.

**Performance Issues**
No performance issues found.

**Playstyle** (If it compatible with how we play)
Yes, due to being an extra unit group we can use them.

**Impacts** (Any extra work/impacts & needed mods)
No impact's as of right now. Might be in the future due to not being updated
Mediafire upload so need to keep track of updates true BI forums
Quality (Quality of mod, graphic, works correct etc.)
I would say graphic wise it looks good. The mod doesn’t work correct with Zeus (information in screenshots).

**Sounds**
The guns I fired sounded good. The helicopter sounded real (in my world, I like the Chinhook) 

**[Screenshot's - imgur](http://imgur.com/a/RPgbZ)**
**Uncompressed Size**
112 MB

**Activity - Development**
Last update - 05 July 2015. Author seems to know little about Arma, ([link of what I mean](https://forums.bistudio.com/topic/143536-idf-israeli-defense-forces-unitscomplete/page-9#entry2886382))

**Personal opinion**
I actually enjoy the mod the units looks good (but ridiculous) but I would be able to play with them :)

**Comment by Fourjays** [comment]
The IDF mod features a number of different Israeli units, including those with the "Mitsnefet", paratroopers and special forces. It adds a new gun, new armor and re-textures some RHS vehicles. It also adds a small number of Hezbollah units. Unfortunately it suffers from a number of bug, the most obvious being the armor not being updated for 1.54. Other bugs include units that are either missing their names or missing entirely in Zeus. The mod has received no updates since last July (despite the 1.54 issue), and the developer has been inactive on the BI forums since that time.

Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=658623850
http://steamcommunity.com/sharedfiles/filedetails/?id=658623898
http://steamcommunity.com/sharedfiles/filedetails/?id=658623990
http://steamcommunity.com/sharedfiles/filedetails/?id=658623940
http://steamcommunity.com/sharedfiles/filedetails/?id=658624095
http://steamcommunity.com/sharedfiles/filedetails/?id=658624148

**Comment by Fourjays** [comment]
Rejected in the meeting on 04/04/2016 due to quality issues.
