### ISSUE TITLE
HLC Springfield 1903A1

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#216]
**Description:**
The Model of 1903 Springfield Rifle is an odd branch of firearms history, in that, it's one of the only legally citable cases of plajorism and Intellectual property theft comitted by a Nation's Federal Arsenal in the 20th century. The Springfield Model 1903 came out of the US Army's need for a new infantry rifle to replace the M1892 Springfield Krag Rifles. While theoretically fine rifles, the Krag ran afoul of it's loading gate mechanism in combat, in particular the Spanish-American War made it's cumbersome nature prominent against the Spanish Mausers(notably The Battle for San Juan Hill).

**Download:** http://www.armaholic.com/page.php?id=30084
**Size:** 59MB

**Comment by CervenBWI** [comment]
What is the reasoning behind having a century-old firearm on our server?

**Comment by Fourjays** [comment]
Suggestion that may provide another option for use as a sniper/marksman rifle in loadouts, particularly those for older time periods. Is a new release from HLC, who we already have/use many weapons from.

**Comment by Tebro** [comment]
It is a nice old rifle alright. The pack contains two rifles, one with a scope and one without, and one type of ammo.

Album: http://imgur.com/a/qw9u9

This image shows a weird bounce that I got on one shot but may be nothing: http://imgur.com/VPy2uCn

**Comment by adios113** [comment]
We can utilise this one for the Vietcong.

**Comment by LordCavac** [comment]
I haven't found any bugs. Firing other rifles side by side I have noticed that after passing through a person's body the trajectory always turns about 30 degrees upward whereas with other snipers the trajectory change is either random or does not occur.

From my testing it is just a sniper rifle that under preforms compared to other options we already have available due to lower clip size, slower rate of fire, and no ability to switch scopes or anything. The scope on the rifle is also incompatible with NVGs.

It  looks nice graphically, but out of place with newer uniforms.

Unless something major comes up I don't really have anything else to say about it.

**Comment by adios113** [comment]
## **Review:**

**HLC's Springfield 1903A1 with two variants made by Toadie.**

The rifle was tested on Virtual Reality map, using `BIS_fnc_traceBullets`
and a firing course with different variety of targets, including Pop-up targets and heavily armored targets respectively at **100m, 200m, 300m, 500m, 700m, 1000m.**

Springfield's effective range historicaly is 1000m. I was using Iron Sights for up to 500m targets and continued the test with the scoped version of the rifle for the 700m and 1000m targets respectively.

**Visual quality**

Springfield 1903A1 comes with two version - standard Infantry rifle with iron sights only and a scoped version for snipers. The reason for that is a different reloading animation required for both version. Standard version is using a clip, sniper version requires the bullets to be loaded in manualy, as you can see in both screenshots:

Standard Infantry Version:
http://steamcommunity.com/sharedfiles/filedetails/?id=645773160
http://steamcommunity.com/id/adiospl93/screenshots/#scrollTop=2206
http://steamcommunity.com/sharedfiles/filedetails/?id=645773180

Sniper Version:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770376
http://steamcommunity.com/sharedfiles/filedetails/?id=645770409

Since the Springfield 1903A1 is a bolt action rifle, it also comes with a nice barrel opening/closing animation:
http://steamcommunity.com/sharedfiles/filedetails/?id=645773160
http://steamcommunity.com/sharedfiles/filedetails/?id=645773091
_`(ignore the error message, it is not related to this mod)`_

Moving on, to overall visual quality, I'd like to remember you that the author of the mod is Toadie, also known from other HLC mods, which are known for one of the best visual, animation and sound quality and its not otherwise in this example. Author delivers with very nicely detailed model of the weapon itself, which you can see in the screenshots below:

http://steamcommunity.com/sharedfiles/filedetails/?id=645769997
http://steamcommunity.com/sharedfiles/filedetails/?id=645770021
http://steamcommunity.com/sharedfiles/filedetails/?id=645770045
http://steamcommunity.com/sharedfiles/filedetails/?id=645770062
http://steamcommunity.com/sharedfiles/filedetails/?id=645770085
http://steamcommunity.com/sharedfiles/filedetails/?id=645770097
http://steamcommunity.com/sharedfiles/filedetails/?id=645770309

**Firing Tests**

While shooting with the Springfield 1903A1, I felt very powerful, even though it is a very old rifle, dating back to WW1 where it was most used and continued to be used even up to Vietnam War.
During the test I had 5 rounds per target. At the beggining i was shooting the pop-up targets with
`BIS_fnc_traceBullets` to track the bullet's trajectory and effectiveness. Here are the results:

100m, Ironsights:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770128
http://steamcommunity.com/sharedfiles/filedetails/?id=645770157
_` (exit paths) `_

200m, Ironsights:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770173
_` (with exit paths behind the target) `_

300m, Ironsights:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770198

500m, Ironsights:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770286

700m, Sniper Rifle:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770423

1000m, Sniper Rifle:
http://steamcommunity.com/sharedfiles/filedetails/?id=645770441

As you can see from the screenshots, the rifle is pretty effective - even more effective than some of the modern sniper rifles we are using. While testing the rifle on living targets, with a very high armor value, the rifle seemed to one shot every single soldier, even 1000m away.
I think its very self explanatory - the rifle uses .30cal rounds, so for me its no wonder it is so effective and in accurate hands it is capable of killing everything around 1km away from you.

Regarding the bullets bouncing off the ground after hitting the target, It is pretty clear from my screenshots why is this happening and is simple as hitting the ground after penetrating the target with low angle, causing the bullet to bounce of it.

**Usefulness in Black Watch International:**

Pretty much none, unless we start doing some vietnam styled ops or there is an actual WW2 mod in our modpack (still no WW2 mods for Arma 3 :( ). I like the rifle very much, I love bolt action rifles, but the only reason I can see for now that we include this rifle in our modpack is sentiment and that is not going to happen. We already have CUP's Lee Enfield, which is much lower quality, but still.

Cheers.

**Comment by Fourjays** [comment]
Rejected in meeting on 21/03/2016 due to lack of usefulness for our operations.
