### ISSUE TITLE
HLC SIG SG510s

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#217]
**Description:**
The SIG SG510 is probably one of the most overlooked rifles of the cold war period. While,arguably, it's not much in the looks department, it's a real brute of a battle rifle, built from the round up for marksman accuracy and extreme-climate reliability. The design of the 510 is directly descended from the AM55 rifle designed by Rudolf Amsler, which borrowed functionality heavily from German WW2 designs (notably the MG42 and FG42, though never in a direct enough fashion to infringe patents).

**Download:** http://www.armaholic.com/page.php?id=30090
**Size:** 59MB

**Comment by wingatex** [comment]
Just tested images will be placed below of some of the different weapons, the gun its self looks and sounds good. Works with different variants of scopes without issue. takes up the same amount of room as an M4 on the screen. Is very powerful because of the round it takes can drop somebody from over 500 yards with one good chest hit. Overall no issues or complaints.

http://steamcommunity.com/sharedfiles/filedetails/?id=651640244
http://steamcommunity.com/sharedfiles/filedetails/?id=651640379
http://steamcommunity.com/sharedfiles/filedetails/?id=651640513

**Comment by Ludvigroosen** [comment]
**Tested (Which map)**
Virtual Arsenal

**Compatibility (If it compatible with the mod pack)**
Yes

**Performance Issues**
None found

**Playstyle (If it compatible with how we play)**
Yes, I believe so, ads some 5 extra weapons.

**Impacts (Any extra work/impacts & needed mods)**
 Not more than usual

**Quality (Quality of mod, graphic, works correct etc.)**
Good, the quality of the mod is good same with graphic. They work as expected
Sounds.  Emits a good sound

**Screenshot's –  [Imgur](http://imgur.com/a/pY8cB)**

**Uncompressed Size**
76,8 MB - unpacked

**Activity - Development**
Yes, the author is still active on the bistudio forum

**Personal opinion**
Seems like a mod with potential

**Comment by Fourjays** [comment]
Rejected in the meeting on 18th July 2016 due to lack of use.
