### ISSUE TITLE
ALiVE Update to v1.0

### ISSUE THREAD

**Issue by adios113** [blackwatchint/modpack#281]
https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/

This release includes a number of fixes since our feature complete Release Candidate in November. Key amongst them is Headless Client integration for Combat Support, fixes to the plugin to avoid persistence failing, fixes to our client connection code, support for custom compositions, updates to player resupply and some other minor fixes - see the full change log below!

There is a long list of maps that people would like to see indexed for ALiVE and unfortunately we simply haven't had the time to include them all in this release. However, we will very soon be in a position to enable community members to index maps so hopefully we can get more cracked then. More details to follow soon!

To celebrate our release we are including a new Johari Bonus Track called Everest. The track is particularly fitting as it's taken our team of dedicated people to reach the summit of ALiVE 1.0! We hope you enjoy it. It features in 2 of the 4 intro missions we have on the Arma 3 main menu, alongside the ALiVE exclusive Arma 3 cover This is War by Johari (note that you easily disable this by removing intro.pbo if it is not your thing).

**Comment by TheGrandVizier** [comment]
This is what they claim is the changelog:

>  Build 1,0
[Main] Added RHS and CUP faction compatibility update
[SUP CS] Fixed Combat support was not working properly due to http://feedback.arma...ew.php?id=26091 (https://github.com/A...live/issues/162 and https://github.com/A...live/issues/140).
[XLIB] Fixed ALiVE_fnc_getPlayerByUIDOnConnect was caught in a loop that never finished (f.e. during HC usage)
[civ_placement] ADDED: custom roadblock compositions can be listed in the array ALiVE_compositions_roadblocks
[mil_command] Updated: Avoid patrol movement waypoints in the sea
[intro] Added ALiVE Bonus track for v1.0 - Everest by Johari
[sys_player] Fixed: Vehicles names defined in the editor are overwritten by sys_player #152
[AliveServer] * 9a98f0e0 - Dump perfmon to a file for debugging purposes * ed54e183 - Show Auth URI in log
[AliveServer] 19c0e3a - Added thread error code to debug output.
[SYS AI SKILL] Fixed ALiVE_fnc_AIskillSetter waiting for AI Skill module even if it wasn't used in the mission http://dev.withsix.com/issues/76331
[sup_player_resupply] made logistics player requests cancellable if still virtual
[SYS CREWINFO] Fixed CrewInfo was always running if playeroptions-module was placed, ignoring the "None" setting in the module parameters.
[AliveServer] - Fixes * [cmdStartALiVE] Fixed typo in error logging * ce7aa4e Fixed a bug where Linux was unabled to do a regex search on large strings. * 1f5e14d Added a thread counter. * a212ff6 Flush logs immediately. * c323c61 Changed the name of Linux plugin.
[sup_player_resupply] added initial functionality to handle multiple player requests, view status on existing requests, cancel existing requests
[AliveServer] Updated plugin to hash 9563efa
[SUP CS] Removed leftover debug lines

**Comment by Relvox** [comment]
uploaded (source: their website)

**Comment by Fourjays** [comment]
Whenever loading a mission created with the newest version of ALiVE, none of the playable slots are available for selection. This can not be replicated with the old modpack. Working assumption it is a result of the newest CBA (#306), as ALiVE is not yet fully compatible with it (https://forums.bistudio.com/topic/187954-alive-advanced-light-infantry-virtual-environment-10-ga/page-11#entry2990505).

Needs more testing for certainty. Assuming this is the cause, ALiVE will be non-functional in our modpack until they release an update.

**Comment by Fourjays** [comment]
We'll be proceeding with this is an accepted known issue. As soon as the ALiVE team release the hotfix it will be made available via the repository.

Waiting for deployment to the live repository.
