### ISSUE TITLE
Investigate selectable/automated side changing

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#345]
Templates currently require the platoon structure is repeated once per faction. This make it difficult to handle various structural changes. If it can be done without any noticable impact to players, it would be better if the side was automatically changed by loadout selection, or a Zeus option,

Any solution must:
- Be transparent to players beyond their normal interactions.
- Handle JIPs so they join with the correct faction.
- Handle deaths/respawns so they return with the correct faction.

**Comment by ShiFoo** [comment]
I would really like to have this. Sadly, the more i think about it, the more problems are coming up. THis could go bad very easily. Especially respawns, leaving the group and such. This could break the gameplay if some people are simply invulnerable because their side is incorrect. I will try something but i dont have high hopes that we can get this to function properly.

**Comment by Fourjays** [comment]
Should we consider this a non-starter and forget it?

**Comment by ShiFoo** [comment]
Yeah, i would discard this for now.

**Comment by Fourjays** [comment]
Closing as impractical.
