### ISSUE TITLE
Killochs Multi-National Pack

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#381]
**Description:**
Killoch's multi-national pack is a retexture pack, which aims to bring a huge variety of Infantry units to your games in a single pack. The pack features 57 "factions", or distinct groups or camouflage patterns, and well over 300 Gear items to achive this, which represent a dozen real world groups, including the USMC, US Army, Russian Federation, Peoples Republic of China, North and South Korea, New Zealand, Australia, Finland, Norway, Germany, Canada, the UK and Ireland and many other fictional Generic groups. Though Intended primarily as a Gear pack, from where you can make your own loadouts, the pack comes with a limited variety of AI units that can be placed in the editor for all 57 Factions (489 AI units) and placeable groups. Understanding the constraints and headaches of creating a Modpack for groups, The filesize has been kept as small as I could and comes in at ~340Mb. The pack has no external Dependencies. 

**Download:** http://www.armaholic.com/page.php?id=26666
**Size:** 317MB

**Comment by abelarno** [comment]
Has anything changed in the mod since a couple of months ago?

"@abelarno Quality is ok-ish, but the spawnable groups they provide are useless (Taliban Fighters are individuals only with no weapons, and Killoch's is vanilla centric). Would require extensive development effort, and we'd have the confusing situation of a load of extra groups that we don't want to use."

**Comment by Fourjays** [comment]
@abelarno Basically, we have the knowledge now to be able to override the weapons with our own choices. Plus I've had a number of loadout suggestions that could utilise these uniforms.

**Comment by Fourjays** [comment]
This was provisionally accepted in the meeting on 11/04/2016, pending testing.

**Comment by abelarno** [comment]
Everything works as advertised. Lots of new uniforms/vests/helmets. Enough to make a bunch of new factions. Spawnable units in both zeus and editor use vanilla weapons. So those either need to be overridden, or not used.

Thumbs up

**Comment by Ludvigroosen** [comment]
**Tested** (What map I tested this on)
Altis

**Compatibility** (If it compatible with the mod pack)
This worked great with our mod pack.

**Performance Issues**
No performance issues found
**Playstyle** (If it compatible with how we play)
Due to being so many different units/uniforms I can for sure see that we can use this inside our mod pack.

**Impacts** (Any extra work/impacts & needed mods)
 Might need to give some of the unit’s other weapons. 

**Quality** (Quality of mod, graphic, works correct etc.)
The quality of the mod is good. Didn’t see any bigger flaws in it. Graphical is good, it’s works as it should and the quality changes from unit to unit. 

**Sounds**
Felt like loads of the units had standard weapons. So sounded normal to me

**Screenshot's - [imgur](http://imgur.com/a/CwEwh)**

**Uncompressed Size**
369 MB

**Activity - Development**
09 December 2015 – Last update, Minor update doh.

**Personal opinion**
I can see this mod getting used on many different ways. The only thing I’m missing is the Swedish infantry. Other than that I really like it.

**Comment by VoicelessPrivate** [comment]
**Mod**
Killoch's multi-national pack.

**Compatibility** 
Modpack:
I didn't find any bug or other problems when I tested this mod with our modpack. With this there were no other issues that i had found.
Playstyle:
I feel like it adds a hole new aspect to who we can play as or against.

**Needs work**
All the units spawn with vanilla guns from the faction that they are under, this means that we will have to chance out some if not all the weapons for all the units. There are a couple of futuristic unit in under the Opfore faction that either need work or removel.

**Looks**
This mod look really good for most of the units, there is a couple of the uniform that it offers that we allready have, where the current uniform is much better. There are also uniform the other way around where what the mod offers are better then what we have. (likes to pic of the uniforms will be down below).

**Personal opinion**
I feel that this mod would add alot of new opportunities for mission-makers. I would have really liked to see a UN unit in this mod, it would have been the finishing touch. I don't like that some of the units spawn without helmets. (The British and other units that chance between helmets or boonie/berets).

**Screenshots**
German uniform (Killoch's mod).
http://imgur.com/hRMylda
German uniform (Our modpack).
http://imgur.com/UtvfNzM
US army Desert/Woodland.
http://imgur.com/BK9hopc
The two on the left are in a multicam uniform. (Left our modpack right Killoch's mod).
The two on the right are in the UCP uniform. (Left our modpack right Killock's mod).
I would prefer the Killoch's mod multicam bur not the Killoch's mod UCP.
These are the futuristic uniforms.
http://imgur.com/KrGUMh1
http://imgur.com/yTicVV7
http://imgur.com/gWOkGwo
http://imgur.com/ATByXdB

**Comment by Fourjays** [comment]
Testing seems to have turned up nothing seriously negative, so this will be going in to the next update.

**Comment by Fourjays** [comment]
Has been uploaded to the test repository, and is ready for deployment.

**Comment by Fourjays** [comment]
Due to the unforeseen problems with configuring this mod for our needs (blackwatchint/addons#31), it is likely going to need to be removed in favour of a more suitable option.

**Comment by Fourjays** [comment]
Changes commited to the test repository, ready for deployment to live.
