### ISSUE TITLE
Theseus Services

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#395]
**Description:**
Theseus Services is a content mod providing a number of assets for Arma 3, aimed at Private Military Company game style, developed around the needs of Theseus Incorporated community. Starting out as a mod by Pomigit, then maintained by BadHabitz with a number of other community developers contributing, it is a re-brand of a highly successful PG Services mod.

**Download:** http://www.armaholic.com/page.php?id=30614
**Size:** 122MB

**Comment by Fourjays** [comment]
This is the direct descendant of the abandoned PG PMC Services mod. Will be accepted automatically on completion of testing.

**Comment by Ludvigroosen** [comment]
**Compatibility**(If it compatible with the mod pack)
It works fine with our current modpack

**Performance Issues**
No performance issues found during the brief testing I did.

**Playstyle**(If it compatible with how we play)
I can see that this mod is fitting our playstyle and we can have some more “Black Ops” Operations.

**Impacts**(Any extra work/impacts & needed mods)
No, it’s a standalone mod. Author of the mod “re-brand of a highly successful PG Services mod.”

**Quality**(Quality of mod, graphic, works correct etc.)
I think this mod has great potential, right now the graphic of this mod is really good, all the “meters” are working. It has no problems running alongside our mod pack

**Sounds**
No comment because no new elements inside the mod. Feels like it builds much on the default arma 3 models. 

[Screenshot's](http://imgur.com/a/HBRi1) 

**Uncompressed Size**
135 MB from Steam Workshop

**Activity - Development**
Released - 17 March 2016, no update since

**Personal opinion**
I really like the mod.

**Comment by Fourjays** [comment]
Uploaded to the test repository, ready for deployment.
