### ISSUE TITLE
RHS: GREF

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/modpack#433]
**Description:**
RHS: GREF aims to expand Arma 3 with various independent fictional and real factions that fall outside of the scope of AFRF and USAF. New units, vehicles and weapons await you!

**Download:** http://www.rhsmods.org/mod/3
**Armaholic:** http://www.armaholic.com/page.php?id=30998
**Size:** 575 MB

**Comment by abelarno** [comment]
In order to test this pack, I had to use the latest version of both other RHS mods. RHS GREF borrows a whole lot from the AFRF pack. Some new vehicles here are just reskins from the other packs.

This pack adds a bunch of new independent factions, all in the style of Chernarus. All the new factions are woodland camo, and the difference between the factions is very subtle. (http://images.akamai.steamusercontent.com/ugc/269469113539657029/6374D038D258B732DA9DCED3C36FAEA6A2C753E0/)

The infantry looks really good, and fuctions as well as expected. There are a bunch of new AK models, with some new attachments, as wel as a Mosin Nagant rifle (http://images.akamai.steamusercontent.com/ugc/269469113539658186/4CA299FE8A52F2F7B7D9CAFDDE5F253E958E1E56/)
The bunch of new vehicle (skins) are a nice addition as well. Especially the UN vehicles.

The biggest issue I have with it right now, is that not all factions have proper spawnable groups. Nevertheless, I think this mod is a worthy addition to our pack. We could use some more alternatives to the russians.

More screenshots:
http://images.akamai.steamusercontent.com/ugc/269469113539658053/11E372658477764ACF2C455D319031A4FADFF1A5/
http://images.akamai.steamusercontent.com/ugc/269469113539657933/09FBC5BF80D01193823A965DC2081EB2E2EDDD4F/
http://images.akamai.steamusercontent.com/ugc/269469113539657787/C771E7C5808C925FFDEAD8EC86C9C22A0F58E77E/
http://images.akamai.steamusercontent.com/ugc/269469113539657518/8DED5C988B4C78AED9016F80B1312CF68C078E2B/
http://images.akamai.steamusercontent.com/ugc/269469113539657415/CAB5B287D671C91251B33918F5F25BA7AE416E1B/
http://images.akamai.steamusercontent.com/ugc/269469113539657185/D89B44DBE9AED450E881A74442DFE81D6D5873EC/

**Comment by Fourjays** [comment]
Been testing this out and have mixed feelings. There are 4-5 new "Chernarus" factions and a UN faction, as well as a couple of new weapons, some vehicle retextures, an Antonov AN-2 and a BRDM. Several items of content from RHS: AFRF/USAF have been moved to GREF as well.

As @abelarno said, the variations between the factions are minimal, even though the actual camos GREF adds are quite varied and could be used to create far more varied independent factions than "50 shades of Chernarus". Some of the factions are just a random collection of varying camo types, and come across more vanilla-like than RHS' typical factions because of the poor gear compositions.

The UN vehicles that are added are pretty good, and could get a lot of use combined with our own UN content. However, again there is a sign of "quantity over quality" here - one vehicle has an amateurish looking texture that I wouldn't associate with the UN (or RHS). Although not spawnable right now, it appears that desert vehicles will be appearing in a future version, as there are several hidden textures viewable in the virtual garage,

There's some definite bright spots amongst this pack, and it will probably get better in the future, but GREF feels like it was rushed and padded to make it "worthy" of being seperated from the AFRF/USAF packs. However, we have little choice to adopt this pack as several items that we make frequent use of have been moved from AFRF/USAF to GREF now.

http://steamcommunity.com/sharedfiles/filedetails/?id=706823822
http://steamcommunity.com/sharedfiles/filedetails/?id=706823764
http://steamcommunity.com/sharedfiles/filedetails/?id=706823631
http://steamcommunity.com/sharedfiles/filedetails/?id=706823700
http://steamcommunity.com/sharedfiles/filedetails/?id=706823578
http://steamcommunity.com/sharedfiles/filedetails/?id=706823509

**Comment by Fourjays** [comment]
Agreed in meeting on 20/06/2016 that this will be accepted into the modpack pending further testing and the specifics of its integration being assessed.

**Comment by Fourjays** [comment]
Uploaded to the test repo, waiting deployment.

**Comment by Fourjays** [comment]
Testing needs to determine all new vehicles added that require ACE cargo and inventory sizes updating.

**Comment by Fourjays** [comment]
A new version (0.4.1.1) has been released.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
