### ISSUE TITLE
ACE Update to v3.6.2

### ISSUE THREAD

**Issue by abelarno** [blackwatchint/modpack#466]
Changelog:
https://github.com/acemod/ACE3/releases/tag/v3.6.2

Download:
https://github.com/acemod/ACE3/releases/download/v3.6.2/ace3_3.6.2.zip

**Comment by Fourjays** [comment]
Need testing to determine how changes will impact gameplay and if there are any major bugs we need to be aware of.

Additional testing needs to be performed on any of our custom content that uses ACE, including resupply boxes and the FOB.

**Comment by Fourjays** [comment]
Be aware that this requires #469 and that failures in other mods are likely. See the CBA issue for more info.

**Comment by Ludvigroosen** [comment]
**Tested (Which map)**
Altis

**Compatibility (If it compatible with the mod pack)**
Current mod pack is not working with ACE update. We will need to update CBA otherwise it breaks. Comcard and Rangecard is gone and some error messages pops. 

**Performance Issues**
No performance issues found. 

**Impacts (Any extra work/impacts & needed mods)**
 Feels like the modpack is not compatible without much work

**Quality (Quality of mod, graphic, works correct etc.)**
Can't repair all of the vehicles. rest of ACE seems to be working.

[Images](http://imgur.com/a/td49z)

**Comment by Fourjays** [comment]
@Ludvigroosen Please test with the latest CBA. As already stated, it *requires* the latest CBA.

**Comment by Fourjays** [comment]
ACE v1.6.1 has been released. Test repo currently has v3.6.0 so will need updating again.

**Comment by Fourjays** [comment]
Latest version upload to the test repo, awaiting deployment.

**Comment by Fourjays** [comment]
Hotfix for ACE released. Issue has been updated accordingly.

**Comment by Fourjays** [comment]
Latest version upload to the test repo, awaiting deployment.
