### ISSUE TITLE
Air Cav Vietnam

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#59]
**Description:**
Air Cav Vietnam is an Arma 3 project aimed at creating the setting and atmosphere around the vietnam war. 

**Download:** https://steamcommunity.com/sharedfiles/filedetails/?id=550873311
**Size:** 1GB

**Comment by Fourjays** [comment]
Has this mod request been obsoleted by UNSUNG (#154)?

**Comment by ShiFoo** [comment]
I just read some comments about the UNSUNG mod on Armaholic. People were complaining about stability issues and that it crashes the server...

**Comment by Fourjays** [comment]
We'll check this out given the rejection of #154.

**Comment by abelarno** [comment]
Mod is looking pretty good.
The mod plays nice with ACE, even tough it seems some parts are missing. Replacing tracks on the m113 for example.

I find the RHS m113's to be of higher visual quality, and they have some more features. On these m113's you can't turn out for example. The driver does have actual windows instead of the horrible PIP system RHS uses tough. It also added a nice weapon on one, the vulcan.

The helicopters have some diversity, and work with the AFM. They are a reskin from the Medium Utility Helicopters mod, and thus work as expected.

The vietcong has a more limited arsenal. It has no vehicles, just infantry and some statics. It would be sufficient tough I think, seeing the setting we would use them in.

The mod works good with zeus, and has predefined groups of vietcong/USA. I doesn't work with ALiVE tough.

The biggest downside i'm finding is that it uses CUP weapons, and therefore uses incompatible ammo with our other weapons.

Like the devs say themselves, its mostly a pack of existing mods, with some reskins here and there.
This means that when something breaks in the future, the ACV devs might not be able to fix it, and might be dependand on the original dev to fix the issue.

What is important to keep in mind with this mod, is that it basically comes with other mods. Like the medium utility helicopters (#187), and the Hellenic Armed Forces airplanes (http://www.armaholic.com/page.php?id=23630), and there does not seem to be any way around that.

**Comment by Ludvigroosen** [comment]
**Compatibility** (If it compatible with the mod pack)
Ground vehicle's seems to be half ACE'S compatible and can’t repair fully (Changed Tiers, couldn't change track's). This mod is compatible with our mod pack, as good as I could test (Alive isn't working on current mod pack) 

**Performance Issues**
No issue’s found. Had no problems running this mod pack. 

**Playstyle** (If it compatible with how we play)
In the time I spent in BWI I never played an “Vietnam” mission so no.

**Impacts** (Any extra work/impacts & needed mods)
Due to this being a mod pack, there’s a chance this creates collisions with current mod pack.

Air Cav Vietnam is using elements from: [**Steam**]( https://steamcommunity.com/sharedfiles/filedetails/?id=550873311)
**Quality** (Quality of mod, graphic, works correct etc.)
The mod seems to be working out quite nice there are some hiccups but it’s still playable (errors on imgur).  Due to this being a mod pack there are different quality on the graphic part, mostly the mod presents has a good graphic quality. 

**Sounds**
Sounds of the weapons I fired sounded good, can’t give a perspective due to never heard some of these weapons.
[**Screenshot's - Imgur**]( http://imgur.com/a/EHG6P)

**Uncompressed Size**
1.29 GB after installation

**Activity - Development**
Quite new mod (uploaded to Workshop 25 Nov 2015). Almost 1 update per month, last update was 12 March.

**Personal opinion**
Due to the removal of Nam i feel like we don’t have the map for this mod pack.
This mod added more units to both OPFOR and BLUFOR. The majority of this mod seems really fun, plenty of vehicles for the BLUFOR side, non for OPFOR.

**Review Score**
4/10 due to the problems with ACE.

**Comment by Fourjays** [comment]
Rejected in meeting on 21/03/2016 due to quality.
