### ISSUE TITLE
FSF Kalu Kahn

### ISSUE THREAD

**Issue by blackwatchint** [blackwatchint/modpack#85]
**Description:**
Who's ready for a trek in the beautifull mountains of FSF Kalu Khan?
In this endless outdoor playground, you'll find steep mountains with cloud-covered peaks great for hiking, biking, and trying to not get killed by those guys here that just appeared over the next ridge. 

Off course, all this is very early work, so there's room for improvement in many aspects of the map.

**Download:** http://www.armaholic.com/page.php?id=26034
**Size:** 230MB

**Comment by karlkarl93** [comment]
This is a pretty big map filled with a whole lot of nothing. It's very well made and I didn't have any issues with it. 

This is very thinly populated with a small ammount of villages and 1 airfield.

**Comment by LordCavac** [comment]
Like karl said, it is a lot of emptiness. Lightly forested and very hilly. There would be almost no opportunity for CQB as the few towns that there are have <20 buildings each. My personal feeling is this map is built with vehicle combat in mind as the sheer lack of cover/empty space would keep engagements at pretty much the maximum effective range of weapons as there is little to use to cover an advance.

I don't feel particularly strong one way or another on this map it just feels empty.

**Comment by Ludvigroosen** [comment]
**Playable**
I would say this map can form some new way of having OP’s due to the dense forests and small towns. But sadly the way we operate as of this review date, I would say no due to the fact that the towns is far apart and quite small, so we basically need some way of transportation.

**Quality (Graphic’s)**
The graphic of this map looks quite nice in my opinion. The boring part is there is an heavy amount of the same tree’s used.

**Performance Issues**
I Normal have 60 fps, on this map I had about 50 fps with one unit spawned. Can’t find that a big problem. This fps was recorded with all the mods that BWI are using.
**Sounds**
Normal sound from ARMA so it sounds good.

**[Screenshots – Link](http://imgur.com/a/h6O80)**

**Size – GB**
.RAR file is 239 MB - 406 MB unzipped.

**Activity – Development**
Latest update - 02 March 2016, Changelog is on 32 on BI forums

**Comment by Fourjays** [comment]
As has been said before, this map is mostly forest covered hills. There are a few small villages dotted around the map, even fewer roads and some airfields spaced around the map. The villages are nicely made, but the lack of any features around them makes it feel empty. The performance seems good, and the area of the map is large for the filesize. 

It's very different from anything else we have, but not sure what kind of ops we could play on it. With the steepness of many of the hills, and the random rock formation, it reminds me of a greener Dariyah. Screenshots:
http://steamcommunity.com/sharedfiles/filedetails/?id=658624620
http://steamcommunity.com/sharedfiles/filedetails/?id=658624711
http://steamcommunity.com/sharedfiles/filedetails/?id=658624781
http://steamcommunity.com/sharedfiles/filedetails/?id=658624855
http://steamcommunity.com/sharedfiles/filedetails/?id=658624938
http://steamcommunity.com/sharedfiles/filedetails/?id=658625021
http://steamcommunity.com/sharedfiles/filedetails/?id=658625187
http://steamcommunity.com/sharedfiles/filedetails/?id=658625379
http://steamcommunity.com/sharedfiles/filedetails/?id=658625300
http://steamcommunity.com/sharedfiles/filedetails/?id=658625106
http://steamcommunity.com/sharedfiles/filedetails/?id=658625454
http://steamcommunity.com/sharedfiles/filedetails/?id=658625504

**Comment by Fourjays** [comment]
Rejected in the meeting on 04/04/2016 due to quality issues.
