### ISSUE TITLE
LAxemanns Dynasound

### ISSUE THREAD

**Issue by ShiFoo** [blackwatchint/modpack#91]
**Description:**
LAxemann proudly presents DynaSound (DS), a new soundmod for ArmA 3 (Released) + public soundmod framework (Coming very soon).

I'm a semi-professional audio designer and DynaSound is my SoundMod for ArmA 3. It currently changes the sound of all weapons and enhances it's sound features with things many other modern games have been doing for a while, e.g. different sounds for different distances, distant explosion sounds, debris sounds inside buildings etc. DynaSound is somewhat special since it emphasizes the so called "Dynamic Range" in audio. Simple put, the Dynamic Range is the difference between the loud and the quiet parts of a sound or a whole mix. Please watch this video if you intend to use DynaSound since it will show you why the Dynamic Range has such an impact on the overall audio feel.

**Download:** http://www.armaholic.com/page.php?id=29810
**Size:** 151MB

**Comment by wingatex** [comment]
The sound of this mod is good but I don't like how it makes your screen twitch when it fires, it is off-putting. The sounds it self-work amazing but is now 200mb. I feel ARMA's in games sounds are pretty good and is not needed. I feel more people need to test this mod out and gain a group consensus as it comes down to what people want. Personally I am happy with the current in game sounds.

**Comment by Fourjays** [comment]
Candidate for inclusion as optional mod.

**Comment by Fourjays** [comment]
Used the same six mini-scenarios as I used for JSRS to test and compare DynaSound to vanilla sounds. The videos can be found below and as before tere will be slight variations because of AI behaviours.

- Vanilla: https://www.dropbox.com/s/wv7uqyazjhue1ld/Arma%203%20SFX%20Comparison%20-%20Vanilla.mp4?dl=0
- DynaSound: 

My thoughts so far:
- Slightly louder environment effects.
- Vehicle audio audible at same range as vanilla.
- IFV gunfire is notably louder than vanilla and audible from a greater range.
- Explosions retain vanilla's deep bass.
- Tank audible at same range with DynaSound as vanilla.
- All gunfire louder than vanilla. The "muffle" has been removed.
- Some weapon noises seem very different. Launcher noise very noticable.
- Distant noises slightly quieter than vanilla.
- Bullet cracks only slightly more noticable than vanilla.

This is a nice mod for the size, but doesn't feel like a huge upgrade over the vanilla sounds. The way some of the weapons sound entirely different, and the increase in volume for all weapons is a little concerning for an optional mod.

**Comment by ShiFoo** [comment]
Errr, as far as i know, only vanilla gun sounds have been altered.Are you sure that, e.g. RHS weapons are affected?

**Comment by Fourjays** [comment]
Yes, all units in the scenarios above are RHS. The difference in weapon sounds is very obvious in the third scenario (approx 2m 30s). Automatic fire and launcher sounds are noticeably very different.

**Comment by Fourjays** [comment]
Rejected in the meeting on 29/03/2016 due to environmental differences and prior adoption of JSRS (#339).
